export { default as About } from './About'
export { default as Education } from './Education'
export { default as Heading } from './Heading'
export { default as Skill } from './Skill'
export { default as SocialLink } from './SocialLink'
export { default as Work } from './Work'
